# travis continuous integration build specification

language: node_js

# versions of node.js to test with:
node_js:
  - "0.11"
  - "0.10"

# npm install is run by default but need to add grunt-ci
before_script:
  - npm install -g grunt-cli

# what to run:
script:
  - npm run-script test
  - npm run-script ci
